baseurl = "http://fak3r.com/"
title = "fak3r"
author = "fak3r"

# Shown in the side menu
copyright = "&copy; 2016&nbsp;All rights reserved"
canonifyurls = true
paginate = 10
theme = "blackburn"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "look out honey, cause I'm using technology"
  brand = "fak3r"
  #googleAnalytics = "Your Google Analytics tracking ID"
  #disqus = "Your Disqus shortname"
  disqus = "fak3r"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04"

[permalinks]
  page = "/:title/"
  #post = "/article/:title/"
  post = "/:year/:month/:day/:title/"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Search"
    pre = "<i class='fa fa-search fa-fw'></i>"
    weight = 2
    identifier = "search"
    url = "/search/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Music"
    pre = "<i class='fa fa-headphones fa-fw'></i>"
    weight = 4
    identifier = "music"
    url = "/music/"
  [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-gamepad fa-fw'></i>"
    weight = 5
    url = "/contact/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.

  # SNS microblogging
  twitter = "fak3r"
  #gnusocial = "*" # Specify href (e.g. https://quitter.se/yourusername)
  #facebook = "*"
  #googleplus = "*"
  #weibo = "*"

  # SNS photo/video sharing
  #instagram = "*"
  flickr = "fak3r"
  #pinterest = "*"
  #youtube = "*"
  #vimeo = "*"
  #vine = "*"
  #slideshare = "*"

  # SNS career oriented
  #linkedin = "*"
  #xing = "*"

  # SNS news
  reddit = "fak3r"
  hackernews = "fak3r"

  # Techie
  github = "philcryer"
  bitbucket = "philcryer"
  #stackoverflow = "*"

  # Other
  keybase = "fak3r"
