#baseurl = "https://fak3r.com/"
#baseurl = "127.0.0.1"
baseurl = "192.168.1.5"
title = "fak3r"
author = "fak3r"

canonifyurls = true
paginate = 10
theme = "hyde"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  description = "slower traffic keep right"
  themeColor = "theme-base-08"
  brand = "fak3r"
  disqus = "fak3r"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04"
  copyright = "Ⓒ 2018 All rights reserved"

[permalinks]
  page = "/:title/"
  #post = "/article/:title/"
  post = "/:year/:month/:day/:title/"

[social]
  twitter = "fak3r"
  #instagram = "*"
  flickr = "fak3r"
  reddit = "fak3r"
  hackernews = "fak3r"
  github = "philcryer"
  bitbucket = "philcryer"
  keybase = "fak3r"
