baseurl = "https://fak3r.com/"
languageCode = "en-us"
title = "fak3r"
theme = "lithium"
#googleAnalytics = ""
#disqusShortname = ""

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "Search"
    url = "/search/"
[[menu.main]]
    name = "Music"
    url = "/music/"
[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Contact"
    url = "/contact/"
#[[menu.main]]
#    name = "GitHub"
#    url = ""
#[[menu.main]]
#    name = "Twitter"
#    url = ""

[params]
    description = "slower traffic keep right"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

    [params.icon]
    #url = "favicon.ico"
    url = "logo.png"

